apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-06-20T11:38:54Z"
  labels:
    app: accounts
  name: accounts
  namespace: sn-labs-abishek6996
  resourceVersion: "1464737129"
  uid: 04c68086-0afd-4249-93e9-f7b4d4820b70
spec:
  clusterIP: 172.21.170.220
  clusterIPs:
  - 172.21.170.220
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: accounts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
